// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: pkg/protocol/messages.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_PACKET_UNKNOWN PacketType = 0
	// Client to Server
	PacketType_C_AUTH_REQUEST PacketType = 1
	PacketType_C_MOVE_INPUT   PacketType = 2
	PacketType_C_SHOOT_INPUT  PacketType = 3
	PacketType_C_MINE_INPUT   PacketType = 4
	PacketType_C_DOCK_INPUT   PacketType = 5
	PacketType_C_BUY_INPUT    PacketType = 6
	PacketType_C_SELL_INPUT   PacketType = 7
	PacketType_C_PING         PacketType = 8
	// Server to Client
	PacketType_S_AUTH_RESPONSE    PacketType = 9
	PacketType_S_WORLD_SNAPSHOT   PacketType = 10
	PacketType_S_DELTA_SNAPSHOT   PacketType = 11
	PacketType_S_DAMAGE_EVENT     PacketType = 12
	PacketType_S_DEATH_EVENT      PacketType = 13
	PacketType_S_CHAT_MESSAGE     PacketType = 14
	PacketType_S_MARKET_DATA      PacketType = 15
	PacketType_S_INVENTORY_UPDATE PacketType = 16
	PacketType_S_PONG             PacketType = 17
	// Corporations & Production (added in Phase 3)
	PacketType_C_CREATE_CORP_REQUEST  PacketType = 18
	PacketType_S_CREATE_CORP_RESPONSE PacketType = 19
	PacketType_C_INVITE_CORP_REQUEST  PacketType = 20
	PacketType_C_JOIN_CORP_REQUEST    PacketType = 21
	PacketType_C_START_REFINE_REQUEST PacketType = 22
	PacketType_C_BUILD_SHIP_REQUEST   PacketType = 23
	PacketType_C_VAULT_ACTION         PacketType = 24
	PacketType_S_VAULT_STATUS         PacketType = 25
	PacketType_C_JOIN_COMBAT_REQUEST  PacketType = 26
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0:  "PACKET_UNKNOWN",
		1:  "C_AUTH_REQUEST",
		2:  "C_MOVE_INPUT",
		3:  "C_SHOOT_INPUT",
		4:  "C_MINE_INPUT",
		5:  "C_DOCK_INPUT",
		6:  "C_BUY_INPUT",
		7:  "C_SELL_INPUT",
		8:  "C_PING",
		9:  "S_AUTH_RESPONSE",
		10: "S_WORLD_SNAPSHOT",
		11: "S_DELTA_SNAPSHOT",
		12: "S_DAMAGE_EVENT",
		13: "S_DEATH_EVENT",
		14: "S_CHAT_MESSAGE",
		15: "S_MARKET_DATA",
		16: "S_INVENTORY_UPDATE",
		17: "S_PONG",
		18: "C_CREATE_CORP_REQUEST",
		19: "S_CREATE_CORP_RESPONSE",
		20: "C_INVITE_CORP_REQUEST",
		21: "C_JOIN_CORP_REQUEST",
		22: "C_START_REFINE_REQUEST",
		23: "C_BUILD_SHIP_REQUEST",
		24: "C_VAULT_ACTION",
		25: "S_VAULT_STATUS",
		26: "C_JOIN_COMBAT_REQUEST",
	}
	PacketType_value = map[string]int32{
		"PACKET_UNKNOWN":         0,
		"C_AUTH_REQUEST":         1,
		"C_MOVE_INPUT":           2,
		"C_SHOOT_INPUT":          3,
		"C_MINE_INPUT":           4,
		"C_DOCK_INPUT":           5,
		"C_BUY_INPUT":            6,
		"C_SELL_INPUT":           7,
		"C_PING":                 8,
		"S_AUTH_RESPONSE":        9,
		"S_WORLD_SNAPSHOT":       10,
		"S_DELTA_SNAPSHOT":       11,
		"S_DAMAGE_EVENT":         12,
		"S_DEATH_EVENT":          13,
		"S_CHAT_MESSAGE":         14,
		"S_MARKET_DATA":          15,
		"S_INVENTORY_UPDATE":     16,
		"S_PONG":                 17,
		"C_CREATE_CORP_REQUEST":  18,
		"S_CREATE_CORP_RESPONSE": 19,
		"C_INVITE_CORP_REQUEST":  20,
		"C_JOIN_CORP_REQUEST":    21,
		"C_START_REFINE_REQUEST": 22,
		"C_BUILD_SHIP_REQUEST":   23,
		"C_VAULT_ACTION":         24,
		"S_VAULT_STATUS":         25,
		"C_JOIN_COMBAT_REQUEST":  26,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_messages_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_pkg_protocol_messages_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Ack           uint32                 `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	AckBitfield   uint32                 `protobuf:"varint,3,opt,name=ack_bitfield,json=ackBitfield,proto3" json:"ack_bitfield,omitempty"`
	Type          PacketType             `protobuf:"varint,4,opt,name=type,proto3,enum=protocol.PacketType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Packet) GetAck() uint32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *Packet) GetAckBitfield() uint32 {
	if x != nil {
		return x.AckBitfield
	}
	return 0
}

func (x *Packet) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_PACKET_UNKNOWN
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Client Messages
type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type MoveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveInput) Reset() {
	*x = MoveInput{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInput) ProtoMessage() {}

func (x *MoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInput.ProtoReflect.Descriptor instead.
func (*MoveInput) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MoveInput) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveInput) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ShootInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShootInput) Reset() {
	*x = ShootInput{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShootInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootInput) ProtoMessage() {}

func (x *ShootInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootInput.ProtoReflect.Descriptor instead.
func (*ShootInput) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ShootInput) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ShootInput) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type MineInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MineInput) Reset() {
	*x = MineInput{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MineInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MineInput) ProtoMessage() {}

func (x *MineInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MineInput.ProtoReflect.Descriptor instead.
func (*MineInput) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MineInput) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MineInput) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type DockInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     uint64                 `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockInput) Reset() {
	*x = DockInput{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockInput) ProtoMessage() {}

func (x *DockInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockInput.ProtoReflect.Descriptor instead.
func (*DockInput) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DockInput) GetStationId() uint64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

type BuyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	StationId     uint64                 `protobuf:"varint,3,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyInput) Reset() {
	*x = BuyInput{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyInput) ProtoMessage() {}

func (x *BuyInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyInput.ProtoReflect.Descriptor instead.
func (*BuyInput) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BuyInput) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *BuyInput) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BuyInput) GetStationId() uint64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

type SellInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	StationId     uint64                 `protobuf:"varint,3,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellInput) Reset() {
	*x = SellInput{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellInput) ProtoMessage() {}

func (x *SellInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellInput.ProtoReflect.Descriptor instead.
func (*SellInput) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SellInput) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *SellInput) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SellInput) GetStationId() uint64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Server Messages
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	EntityId      uint64                 `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{9}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthResponse) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *AuthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type EntitySnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EntityId          uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType        uint32                 `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // matches domain.EntityType
	X                 float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                 float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Rotation          float32                `protobuf:"fixed32,5,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Vx                float32                `protobuf:"fixed32,6,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy                float32                `protobuf:"fixed32,7,opt,name=vy,proto3" json:"vy,omitempty"`
	Hp                int32                  `protobuf:"varint,8,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp             int32                  `protobuf:"varint,9,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Shield            int32                  `protobuf:"varint,10,opt,name=shield,proto3" json:"shield,omitempty"`
	MaxShield         int32                  `protobuf:"varint,11,opt,name=max_shield,json=maxShield,proto3" json:"max_shield,omitempty"`
	Name              string                 `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	FactionId         uint32                 `protobuf:"varint,13,opt,name=faction_id,json=factionId,proto3" json:"faction_id,omitempty"`
	CorpId            uint32                 `protobuf:"varint,14,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	TargetId          uint64                 `protobuf:"varint,15,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IsShooting        bool                   `protobuf:"varint,16,opt,name=is_shooting,json=isShooting,proto3" json:"is_shooting,omitempty"`
	IsMining          bool                   `protobuf:"varint,17,opt,name=is_mining,json=isMining,proto3" json:"is_mining,omitempty"`
	RefineryActive    bool                   `protobuf:"varint,18,opt,name=refinery_active,json=refineryActive,proto3" json:"refinery_active,omitempty"`
	ShipyardQueueLen  int32                  `protobuf:"varint,19,opt,name=shipyard_queue_len,json=shipyardQueueLen,proto3" json:"shipyard_queue_len,omitempty"`
	ShipType          string                 `protobuf:"bytes,20,opt,name=ship_type,json=shipType,proto3" json:"ship_type,omitempty"`
	PriceIron         int32                  `protobuf:"varint,21,opt,name=price_iron,json=priceIron,proto3" json:"price_iron,omitempty"`
	PriceTitanium     int32                  `protobuf:"varint,22,opt,name=price_titanium,json=priceTitanium,proto3" json:"price_titanium,omitempty"`
	PriceCrystal      int32                  `protobuf:"varint,23,opt,name=price_crystal,json=priceCrystal,proto3" json:"price_crystal,omitempty"`
	QtyIron           int32                  `protobuf:"varint,24,opt,name=qty_iron,json=qtyIron,proto3" json:"qty_iron,omitempty"`
	QtyTitanium       int32                  `protobuf:"varint,25,opt,name=qty_titanium,json=qtyTitanium,proto3" json:"qty_titanium,omitempty"`
	QtyCrystal        int32                  `protobuf:"varint,26,opt,name=qty_crystal,json=qtyCrystal,proto3" json:"qty_crystal,omitempty"`
	QtyIronPlates     int32                  `protobuf:"varint,27,opt,name=qty_iron_plates,json=qtyIronPlates,proto3" json:"qty_iron_plates,omitempty"`
	QtyTitaniumPlates int32                  `protobuf:"varint,28,opt,name=qty_titanium_plates,json=qtyTitaniumPlates,proto3" json:"qty_titanium_plates,omitempty"`
	CargoCapacity     int32                  `protobuf:"varint,29,opt,name=cargo_capacity,json=cargoCapacity,proto3" json:"cargo_capacity,omitempty"`
	CargoLoad         int32                  `protobuf:"varint,30,opt,name=cargo_load,json=cargoLoad,proto3" json:"cargo_load,omitempty"`
	Credits           int64                  `protobuf:"varint,31,opt,name=credits,proto3" json:"credits,omitempty"`
	QtySiliconWafers  int32                  `protobuf:"varint,32,opt,name=qty_silicon_wafers,json=qtySiliconWafers,proto3" json:"qty_silicon_wafers,omitempty"`
	QtyFuelCells      int32                  `protobuf:"varint,33,opt,name=qty_fuel_cells,json=qtyFuelCells,proto3" json:"qty_fuel_cells,omitempty"`
	QtyMicrochips     int32                  `protobuf:"varint,34,opt,name=qty_microchips,json=qtyMicrochips,proto3" json:"qty_microchips,omitempty"`
	QtyEnergyCoils    int32                  `protobuf:"varint,35,opt,name=qty_energy_coils,json=qtyEnergyCoils,proto3" json:"qty_energy_coils,omitempty"`
	QtyLaserCannon    int32                  `protobuf:"varint,36,opt,name=qty_laser_cannon,json=qtyLaserCannon,proto3" json:"qty_laser_cannon,omitempty"`
	QtyMiningLaser    int32                  `protobuf:"varint,37,opt,name=qty_mining_laser,json=qtyMiningLaser,proto3" json:"qty_mining_laser,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EntitySnapshot) Reset() {
	*x = EntitySnapshot{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySnapshot) ProtoMessage() {}

func (x *EntitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySnapshot.ProtoReflect.Descriptor instead.
func (*EntitySnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{10}
}

func (x *EntitySnapshot) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntitySnapshot) GetEntityType() uint32 {
	if x != nil {
		return x.EntityType
	}
	return 0
}

func (x *EntitySnapshot) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EntitySnapshot) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EntitySnapshot) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *EntitySnapshot) GetVx() float32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *EntitySnapshot) GetVy() float32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *EntitySnapshot) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntitySnapshot) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *EntitySnapshot) GetShield() int32 {
	if x != nil {
		return x.Shield
	}
	return 0
}

func (x *EntitySnapshot) GetMaxShield() int32 {
	if x != nil {
		return x.MaxShield
	}
	return 0
}

func (x *EntitySnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntitySnapshot) GetFactionId() uint32 {
	if x != nil {
		return x.FactionId
	}
	return 0
}

func (x *EntitySnapshot) GetCorpId() uint32 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

func (x *EntitySnapshot) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *EntitySnapshot) GetIsShooting() bool {
	if x != nil {
		return x.IsShooting
	}
	return false
}

func (x *EntitySnapshot) GetIsMining() bool {
	if x != nil {
		return x.IsMining
	}
	return false
}

func (x *EntitySnapshot) GetRefineryActive() bool {
	if x != nil {
		return x.RefineryActive
	}
	return false
}

func (x *EntitySnapshot) GetShipyardQueueLen() int32 {
	if x != nil {
		return x.ShipyardQueueLen
	}
	return 0
}

func (x *EntitySnapshot) GetShipType() string {
	if x != nil {
		return x.ShipType
	}
	return ""
}

func (x *EntitySnapshot) GetPriceIron() int32 {
	if x != nil {
		return x.PriceIron
	}
	return 0
}

func (x *EntitySnapshot) GetPriceTitanium() int32 {
	if x != nil {
		return x.PriceTitanium
	}
	return 0
}

func (x *EntitySnapshot) GetPriceCrystal() int32 {
	if x != nil {
		return x.PriceCrystal
	}
	return 0
}

func (x *EntitySnapshot) GetQtyIron() int32 {
	if x != nil {
		return x.QtyIron
	}
	return 0
}

func (x *EntitySnapshot) GetQtyTitanium() int32 {
	if x != nil {
		return x.QtyTitanium
	}
	return 0
}

func (x *EntitySnapshot) GetQtyCrystal() int32 {
	if x != nil {
		return x.QtyCrystal
	}
	return 0
}

func (x *EntitySnapshot) GetQtyIronPlates() int32 {
	if x != nil {
		return x.QtyIronPlates
	}
	return 0
}

func (x *EntitySnapshot) GetQtyTitaniumPlates() int32 {
	if x != nil {
		return x.QtyTitaniumPlates
	}
	return 0
}

func (x *EntitySnapshot) GetCargoCapacity() int32 {
	if x != nil {
		return x.CargoCapacity
	}
	return 0
}

func (x *EntitySnapshot) GetCargoLoad() int32 {
	if x != nil {
		return x.CargoLoad
	}
	return 0
}

func (x *EntitySnapshot) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *EntitySnapshot) GetQtySiliconWafers() int32 {
	if x != nil {
		return x.QtySiliconWafers
	}
	return 0
}

func (x *EntitySnapshot) GetQtyFuelCells() int32 {
	if x != nil {
		return x.QtyFuelCells
	}
	return 0
}

func (x *EntitySnapshot) GetQtyMicrochips() int32 {
	if x != nil {
		return x.QtyMicrochips
	}
	return 0
}

func (x *EntitySnapshot) GetQtyEnergyCoils() int32 {
	if x != nil {
		return x.QtyEnergyCoils
	}
	return 0
}

func (x *EntitySnapshot) GetQtyLaserCannon() int32 {
	if x != nil {
		return x.QtyLaserCannon
	}
	return 0
}

func (x *EntitySnapshot) GetQtyMiningLaser() int32 {
	if x != nil {
		return x.QtyMiningLaser
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Entities      []*EntitySnapshot      `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{11}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetEntities() []*EntitySnapshot {
	if x != nil {
		return x.Entities
	}
	return nil
}

type DeltaSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tick              uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	UpdatedEntities   []*EntitySnapshot      `protobuf:"bytes,2,rep,name=updated_entities,json=updatedEntities,proto3" json:"updated_entities,omitempty"`
	DestroyedEntities []uint64               `protobuf:"varint,3,rep,packed,name=destroyed_entities,json=destroyedEntities,proto3" json:"destroyed_entities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeltaSnapshot) Reset() {
	*x = DeltaSnapshot{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaSnapshot) ProtoMessage() {}

func (x *DeltaSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaSnapshot.ProtoReflect.Descriptor instead.
func (*DeltaSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{12}
}

func (x *DeltaSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *DeltaSnapshot) GetUpdatedEntities() []*EntitySnapshot {
	if x != nil {
		return x.UpdatedEntities
	}
	return nil
}

func (x *DeltaSnapshot) GetDestroyedEntities() []uint64 {
	if x != nil {
		return x.DestroyedEntities
	}
	return nil
}

type DamageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    uint64                 `protobuf:"varint,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int32                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	IsKilled      bool                   `protobuf:"varint,4,opt,name=is_killed,json=isKilled,proto3" json:"is_killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DamageEvent) Reset() {
	*x = DamageEvent{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DamageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageEvent) ProtoMessage() {}

func (x *DamageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageEvent.ProtoReflect.Descriptor instead.
func (*DamageEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{13}
}

func (x *DamageEvent) GetAttackerId() uint64 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *DamageEvent) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *DamageEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *DamageEvent) GetIsKilled() bool {
	if x != nil {
		return x.IsKilled
	}
	return false
}

type DeathEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeathEvent) Reset() {
	*x = DeathEvent{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathEvent) ProtoMessage() {}

func (x *DeathEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathEvent.ProtoReflect.Descriptor instead.
func (*DeathEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{14}
}

func (x *DeathEvent) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MarketItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Price         int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketItem) Reset() {
	*x = MarketItem{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketItem) ProtoMessage() {}

func (x *MarketItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketItem.ProtoReflect.Descriptor instead.
func (*MarketItem) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{16}
}

func (x *MarketItem) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *MarketItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketItem) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type MarketData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MarketItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketData) Reset() {
	*x = MarketData{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketData) ProtoMessage() {}

func (x *MarketData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketData.ProtoReflect.Descriptor instead.
func (*MarketData) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{17}
}

func (x *MarketData) GetItems() []*MarketItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemInstanceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DefinitionId  uint32                 `protobuf:"varint,2,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LocationType  string                 `protobuf:"bytes,4,opt,name=location_type,json=locationType,proto3" json:"location_type,omitempty"`
	LocationId    uint64                 `protobuf:"varint,5,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Name          string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Stackable     bool                   `protobuf:"varint,10,opt,name=stackable,proto3" json:"stackable,omitempty"`
	Volume        float32                `protobuf:"fixed32,11,opt,name=volume,proto3" json:"volume,omitempty"`
	MetaDataJson  string                 `protobuf:"bytes,12,opt,name=meta_data_json,json=metaDataJson,proto3" json:"meta_data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInstanceProto) Reset() {
	*x = ItemInstanceProto{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInstanceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInstanceProto) ProtoMessage() {}

func (x *ItemInstanceProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInstanceProto.ProtoReflect.Descriptor instead.
func (*ItemInstanceProto) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ItemInstanceProto) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemInstanceProto) GetDefinitionId() uint32 {
	if x != nil {
		return x.DefinitionId
	}
	return 0
}

func (x *ItemInstanceProto) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemInstanceProto) GetLocationType() string {
	if x != nil {
		return x.LocationType
	}
	return ""
}

func (x *ItemInstanceProto) GetLocationId() uint64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *ItemInstanceProto) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ItemInstanceProto) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ItemInstanceProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemInstanceProto) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ItemInstanceProto) GetStackable() bool {
	if x != nil {
		return x.Stackable
	}
	return false
}

func (x *ItemInstanceProto) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *ItemInstanceProto) GetMetaDataJson() string {
	if x != nil {
		return x.MetaDataJson
	}
	return ""
}

type InventoryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credits       int64                  `protobuf:"varint,1,opt,name=credits,proto3" json:"credits,omitempty"`
	Cargo         []*ItemInstanceProto   `protobuf:"bytes,2,rep,name=cargo,proto3" json:"cargo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryUpdate) Reset() {
	*x = InventoryUpdate{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUpdate) ProtoMessage() {}

func (x *InventoryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUpdate.ProtoReflect.Descriptor instead.
func (*InventoryUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{19}
}

func (x *InventoryUpdate) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *InventoryUpdate) GetCargo() []*ItemInstanceProto {
	if x != nil {
		return x.Cargo
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{20}
}

func (x *Pong) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ServerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Type          PacketType             `protobuf:"varint,2,opt,name=type,proto3,enum=protocol.PacketType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{21}
}

func (x *ServerCommand) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ServerCommand) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_PACKET_UNKNOWN
}

func (x *ServerCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PlayerMigrationPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X               float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y               float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Rotation        float32                `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Vx              float32                `protobuf:"fixed32,5,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy              float32                `protobuf:"fixed32,6,opt,name=vy,proto3" json:"vy,omitempty"`
	Hp              int32                  `protobuf:"varint,7,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp           int32                  `protobuf:"varint,8,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Shield          int32                  `protobuf:"varint,9,opt,name=shield,proto3" json:"shield,omitempty"`
	MaxShield       int32                  `protobuf:"varint,10,opt,name=max_shield,json=maxShield,proto3" json:"max_shield,omitempty"`
	ShieldRegenRate float32                `protobuf:"fixed32,11,opt,name=shield_regen_rate,json=shieldRegenRate,proto3" json:"shield_regen_rate,omitempty"`
	WeaponType      string                 `protobuf:"bytes,12,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	WeaponDamage    int32                  `protobuf:"varint,13,opt,name=weapon_damage,json=weaponDamage,proto3" json:"weapon_damage,omitempty"`
	WeaponRange     float32                `protobuf:"fixed32,14,opt,name=weapon_range,json=weaponRange,proto3" json:"weapon_range,omitempty"`
	WeaponCooldown  float32                `protobuf:"fixed32,15,opt,name=weapon_cooldown,json=weaponCooldown,proto3" json:"weapon_cooldown,omitempty"`
	CargoCapacity   int32                  `protobuf:"varint,16,opt,name=cargo_capacity,json=cargoCapacity,proto3" json:"cargo_capacity,omitempty"`
	CargoItems      []*ItemInstanceProto   `protobuf:"bytes,17,rep,name=cargo_items,json=cargoItems,proto3" json:"cargo_items,omitempty"`
	MiningPower     float32                `protobuf:"fixed32,18,opt,name=mining_power,json=miningPower,proto3" json:"mining_power,omitempty"`
	MiningRange     float32                `protobuf:"fixed32,19,opt,name=mining_range,json=miningRange,proto3" json:"mining_range,omitempty"`
	ShipType        string                 `protobuf:"bytes,20,opt,name=ship_type,json=shipType,proto3" json:"ship_type,omitempty"`
	MaxSpeed        float32                `protobuf:"fixed32,21,opt,name=max_speed,json=maxSpeed,proto3" json:"max_speed,omitempty"`
	TurnRate        float32                `protobuf:"fixed32,22,opt,name=turn_rate,json=turnRate,proto3" json:"turn_rate,omitempty"`
	AccountId       uint64                 `protobuf:"varint,23,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PlayerName      string                 `protobuf:"bytes,24,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Credits         int64                  `protobuf:"varint,25,opt,name=credits,proto3" json:"credits,omitempty"`
	SessionId       string                 `protobuf:"bytes,26,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FactionId       uint32                 `protobuf:"varint,27,opt,name=faction_id,json=factionId,proto3" json:"faction_id,omitempty"`
	IsNpc           bool                   `protobuf:"varint,28,opt,name=is_npc,json=isNpc,proto3" json:"is_npc,omitempty"`
	AiBehavior      string                 `protobuf:"bytes,29,opt,name=ai_behavior,json=aiBehavior,proto3" json:"ai_behavior,omitempty"`
	AiTargetId      uint64                 `protobuf:"varint,30,opt,name=ai_target_id,json=aiTargetId,proto3" json:"ai_target_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerMigrationPayload) Reset() {
	*x = PlayerMigrationPayload{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMigrationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMigrationPayload) ProtoMessage() {}

func (x *PlayerMigrationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMigrationPayload.ProtoReflect.Descriptor instead.
func (*PlayerMigrationPayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerMigrationPayload) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerMigrationPayload) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMigrationPayload) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerMigrationPayload) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *PlayerMigrationPayload) GetVx() float32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *PlayerMigrationPayload) GetVy() float32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *PlayerMigrationPayload) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerMigrationPayload) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PlayerMigrationPayload) GetShield() int32 {
	if x != nil {
		return x.Shield
	}
	return 0
}

func (x *PlayerMigrationPayload) GetMaxShield() int32 {
	if x != nil {
		return x.MaxShield
	}
	return 0
}

func (x *PlayerMigrationPayload) GetShieldRegenRate() float32 {
	if x != nil {
		return x.ShieldRegenRate
	}
	return 0
}

func (x *PlayerMigrationPayload) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *PlayerMigrationPayload) GetWeaponDamage() int32 {
	if x != nil {
		return x.WeaponDamage
	}
	return 0
}

func (x *PlayerMigrationPayload) GetWeaponRange() float32 {
	if x != nil {
		return x.WeaponRange
	}
	return 0
}

func (x *PlayerMigrationPayload) GetWeaponCooldown() float32 {
	if x != nil {
		return x.WeaponCooldown
	}
	return 0
}

func (x *PlayerMigrationPayload) GetCargoCapacity() int32 {
	if x != nil {
		return x.CargoCapacity
	}
	return 0
}

func (x *PlayerMigrationPayload) GetCargoItems() []*ItemInstanceProto {
	if x != nil {
		return x.CargoItems
	}
	return nil
}

func (x *PlayerMigrationPayload) GetMiningPower() float32 {
	if x != nil {
		return x.MiningPower
	}
	return 0
}

func (x *PlayerMigrationPayload) GetMiningRange() float32 {
	if x != nil {
		return x.MiningRange
	}
	return 0
}

func (x *PlayerMigrationPayload) GetShipType() string {
	if x != nil {
		return x.ShipType
	}
	return ""
}

func (x *PlayerMigrationPayload) GetMaxSpeed() float32 {
	if x != nil {
		return x.MaxSpeed
	}
	return 0
}

func (x *PlayerMigrationPayload) GetTurnRate() float32 {
	if x != nil {
		return x.TurnRate
	}
	return 0
}

func (x *PlayerMigrationPayload) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerMigrationPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerMigrationPayload) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *PlayerMigrationPayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlayerMigrationPayload) GetFactionId() uint32 {
	if x != nil {
		return x.FactionId
	}
	return 0
}

func (x *PlayerMigrationPayload) GetIsNpc() bool {
	if x != nil {
		return x.IsNpc
	}
	return false
}

func (x *PlayerMigrationPayload) GetAiBehavior() string {
	if x != nil {
		return x.AiBehavior
	}
	return ""
}

func (x *PlayerMigrationPayload) GetAiTargetId() uint64 {
	if x != nil {
		return x.AiTargetId
	}
	return 0
}

type SystemTransferRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	PlayerId       uint64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetSystemId uint32                  `protobuf:"varint,2,opt,name=target_system_id,json=targetSystemId,proto3" json:"target_system_id,omitempty"`
	SpawnX         float32                 `protobuf:"fixed32,3,opt,name=spawn_x,json=spawnX,proto3" json:"spawn_x,omitempty"`
	SpawnY         float32                 `protobuf:"fixed32,4,opt,name=spawn_y,json=spawnY,proto3" json:"spawn_y,omitempty"`
	Payload        *PlayerMigrationPayload `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemTransferRequest) Reset() {
	*x = SystemTransferRequest{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemTransferRequest) ProtoMessage() {}

func (x *SystemTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemTransferRequest.ProtoReflect.Descriptor instead.
func (*SystemTransferRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{23}
}

func (x *SystemTransferRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *SystemTransferRequest) GetTargetSystemId() uint32 {
	if x != nil {
		return x.TargetSystemId
	}
	return 0
}

func (x *SystemTransferRequest) GetSpawnX() float32 {
	if x != nil {
		return x.SpawnX
	}
	return 0
}

func (x *SystemTransferRequest) GetSpawnY() float32 {
	if x != nil {
		return x.SpawnY
	}
	return 0
}

func (x *SystemTransferRequest) GetPayload() *PlayerMigrationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SystemTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemTransferResponse) Reset() {
	*x = SystemTransferResponse{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemTransferResponse) ProtoMessage() {}

func (x *SystemTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemTransferResponse.ProtoReflect.Descriptor instead.
func (*SystemTransferResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{24}
}

func (x *SystemTransferResponse) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *SystemTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SystemTransferResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreateCorpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCorpRequest) Reset() {
	*x = CreateCorpRequest{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCorpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCorpRequest) ProtoMessage() {}

func (x *CreateCorpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCorpRequest.ProtoReflect.Descriptor instead.
func (*CreateCorpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{25}
}

func (x *CreateCorpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCorpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CorpId        uint32                 `protobuf:"varint,2,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCorpResponse) Reset() {
	*x = CreateCorpResponse{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCorpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCorpResponse) ProtoMessage() {}

func (x *CreateCorpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCorpResponse.ProtoReflect.Descriptor instead.
func (*CreateCorpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{26}
}

func (x *CreateCorpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCorpResponse) GetCorpId() uint32 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

func (x *CreateCorpResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type InviteCorpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteeId     uint64                 `protobuf:"varint,1,opt,name=invitee_id,json=inviteeId,proto3" json:"invitee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteCorpRequest) Reset() {
	*x = InviteCorpRequest{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteCorpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteCorpRequest) ProtoMessage() {}

func (x *InviteCorpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteCorpRequest.ProtoReflect.Descriptor instead.
func (*InviteCorpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{27}
}

func (x *InviteCorpRequest) GetInviteeId() uint64 {
	if x != nil {
		return x.InviteeId
	}
	return 0
}

type JoinCorpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorpId        uint32                 `protobuf:"varint,1,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCorpRequest) Reset() {
	*x = JoinCorpRequest{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCorpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCorpRequest) ProtoMessage() {}

func (x *JoinCorpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCorpRequest.ProtoReflect.Descriptor instead.
func (*JoinCorpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{28}
}

func (x *JoinCorpRequest) GetCorpId() uint32 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

type StartRefineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     uint64                 `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRefineRequest) Reset() {
	*x = StartRefineRequest{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRefineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRefineRequest) ProtoMessage() {}

func (x *StartRefineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRefineRequest.ProtoReflect.Descriptor instead.
func (*StartRefineRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{29}
}

func (x *StartRefineRequest) GetStationId() uint64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *StartRefineRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *StartRefineRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BuildShipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     uint64                 `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	ShipType      string                 `protobuf:"bytes,2,opt,name=ship_type,json=shipType,proto3" json:"ship_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildShipRequest) Reset() {
	*x = BuildShipRequest{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildShipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildShipRequest) ProtoMessage() {}

func (x *BuildShipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildShipRequest.ProtoReflect.Descriptor instead.
func (*BuildShipRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{30}
}

func (x *BuildShipRequest) GetStationId() uint64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *BuildShipRequest) GetShipType() string {
	if x != nil {
		return x.ShipType
	}
	return ""
}

type VaultAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     uint64                 `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	VaultType     string                 `protobuf:"bytes,4,opt,name=vault_type,json=vaultType,proto3" json:"vault_type,omitempty"`    // "personal" or "corporate"
	ActionType    string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // "deposit" or "withdraw"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultAction) Reset() {
	*x = VaultAction{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultAction) ProtoMessage() {}

func (x *VaultAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultAction.ProtoReflect.Descriptor instead.
func (*VaultAction) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{31}
}

func (x *VaultAction) GetStationId() uint64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *VaultAction) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *VaultAction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *VaultAction) GetVaultType() string {
	if x != nil {
		return x.VaultType
	}
	return ""
}

func (x *VaultAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

type VaultStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StationId      uint64                 `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	PersonalItems  []*ItemInstanceProto   `protobuf:"bytes,2,rep,name=personal_items,json=personalItems,proto3" json:"personal_items,omitempty"`
	CorporateItems []*ItemInstanceProto   `protobuf:"bytes,3,rep,name=corporate_items,json=corporateItems,proto3" json:"corporate_items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VaultStatus) Reset() {
	*x = VaultStatus{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultStatus) ProtoMessage() {}

func (x *VaultStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultStatus.ProtoReflect.Descriptor instead.
func (*VaultStatus) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{32}
}

func (x *VaultStatus) GetStationId() uint64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *VaultStatus) GetPersonalItems() []*ItemInstanceProto {
	if x != nil {
		return x.PersonalItems
	}
	return nil
}

func (x *VaultStatus) GetCorporateItems() []*ItemInstanceProto {
	if x != nil {
		return x.CorporateItems
	}
	return nil
}

type JoinCombatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CombatInstanceId uint32                 `protobuf:"varint,1,opt,name=combat_instance_id,json=combatInstanceId,proto3" json:"combat_instance_id,omitempty"`
	AlignWithFleetId uint64                 `protobuf:"varint,2,opt,name=align_with_fleet_id,json=alignWithFleetId,proto3" json:"align_with_fleet_id,omitempty"` // 0 for FFA (free for all)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinCombatRequest) Reset() {
	*x = JoinCombatRequest{}
	mi := &file_pkg_protocol_messages_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCombatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCombatRequest) ProtoMessage() {}

func (x *JoinCombatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_messages_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCombatRequest.ProtoReflect.Descriptor instead.
func (*JoinCombatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_messages_proto_rawDescGZIP(), []int{33}
}

func (x *JoinCombatRequest) GetCombatInstanceId() uint32 {
	if x != nil {
		return x.CombatInstanceId
	}
	return 0
}

func (x *JoinCombatRequest) GetAlignWithFleetId() uint64 {
	if x != nil {
		return x.AlignWithFleetId
	}
	return 0
}

var File_pkg_protocol_messages_proto protoreflect.FileDescriptor

const file_pkg_protocol_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/protocol/messages.proto\x12\bprotocol\"\x9d\x01\n" +
	"\x06Packet\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\rR\x03ack\x12!\n" +
	"\fack_bitfield\x18\x03 \x01(\rR\vackBitfield\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.protocol.PacketTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"?\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"'\n" +
	"\tMoveInput\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"A\n" +
	"\n" +
	"ShootInput\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\"@\n" +
	"\tMineInput\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\"*\n" +
	"\tDockInput\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x04R\tstationId\"]\n" +
	"\bBuyInput\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x1d\n" +
	"\n" +
	"station_id\x18\x03 \x01(\x04R\tstationId\"^\n" +
	"\tSellInput\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x1d\n" +
	"\n" +
	"station_id\x18\x03 \x01(\x04R\tstationId\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\"\x8f\x01\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x04R\bentityId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x9a\t\n" +
	"\x0eEntitySnapshot\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\rR\n" +
	"entityType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x1a\n" +
	"\brotation\x18\x05 \x01(\x02R\brotation\x12\x0e\n" +
	"\x02vx\x18\x06 \x01(\x02R\x02vx\x12\x0e\n" +
	"\x02vy\x18\a \x01(\x02R\x02vy\x12\x0e\n" +
	"\x02hp\x18\b \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\t \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06shield\x18\n" +
	" \x01(\x05R\x06shield\x12\x1d\n" +
	"\n" +
	"max_shield\x18\v \x01(\x05R\tmaxShield\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"faction_id\x18\r \x01(\rR\tfactionId\x12\x17\n" +
	"\acorp_id\x18\x0e \x01(\rR\x06corpId\x12\x1b\n" +
	"\ttarget_id\x18\x0f \x01(\x04R\btargetId\x12\x1f\n" +
	"\vis_shooting\x18\x10 \x01(\bR\n" +
	"isShooting\x12\x1b\n" +
	"\tis_mining\x18\x11 \x01(\bR\bisMining\x12'\n" +
	"\x0frefinery_active\x18\x12 \x01(\bR\x0erefineryActive\x12,\n" +
	"\x12shipyard_queue_len\x18\x13 \x01(\x05R\x10shipyardQueueLen\x12\x1b\n" +
	"\tship_type\x18\x14 \x01(\tR\bshipType\x12\x1d\n" +
	"\n" +
	"price_iron\x18\x15 \x01(\x05R\tpriceIron\x12%\n" +
	"\x0eprice_titanium\x18\x16 \x01(\x05R\rpriceTitanium\x12#\n" +
	"\rprice_crystal\x18\x17 \x01(\x05R\fpriceCrystal\x12\x19\n" +
	"\bqty_iron\x18\x18 \x01(\x05R\aqtyIron\x12!\n" +
	"\fqty_titanium\x18\x19 \x01(\x05R\vqtyTitanium\x12\x1f\n" +
	"\vqty_crystal\x18\x1a \x01(\x05R\n" +
	"qtyCrystal\x12&\n" +
	"\x0fqty_iron_plates\x18\x1b \x01(\x05R\rqtyIronPlates\x12.\n" +
	"\x13qty_titanium_plates\x18\x1c \x01(\x05R\x11qtyTitaniumPlates\x12%\n" +
	"\x0ecargo_capacity\x18\x1d \x01(\x05R\rcargoCapacity\x12\x1d\n" +
	"\n" +
	"cargo_load\x18\x1e \x01(\x05R\tcargoLoad\x12\x18\n" +
	"\acredits\x18\x1f \x01(\x03R\acredits\x12,\n" +
	"\x12qty_silicon_wafers\x18  \x01(\x05R\x10qtySiliconWafers\x12$\n" +
	"\x0eqty_fuel_cells\x18! \x01(\x05R\fqtyFuelCells\x12%\n" +
	"\x0eqty_microchips\x18\" \x01(\x05R\rqtyMicrochips\x12(\n" +
	"\x10qty_energy_coils\x18# \x01(\x05R\x0eqtyEnergyCoils\x12(\n" +
	"\x10qty_laser_cannon\x18$ \x01(\x05R\x0eqtyLaserCannon\x12(\n" +
	"\x10qty_mining_laser\x18% \x01(\x05R\x0eqtyMiningLaser\"Y\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x124\n" +
	"\bentities\x18\x02 \x03(\v2\x18.protocol.EntitySnapshotR\bentities\"\x97\x01\n" +
	"\rDeltaSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12C\n" +
	"\x10updated_entities\x18\x02 \x03(\v2\x18.protocol.EntitySnapshotR\x0fupdatedEntities\x12-\n" +
	"\x12destroyed_entities\x18\x03 \x03(\x04R\x11destroyedEntities\"\x80\x01\n" +
	"\vDamageEvent\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\x04R\n" +
	"attackerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x05R\x06damage\x12\x1b\n" +
	"\tis_killed\x18\x04 \x01(\bR\bisKilled\")\n" +
	"\n" +
	"DeathEvent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\"?\n" +
	"\vChatMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\n" +
	"MarketItem\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\"8\n" +
	"\n" +
	"MarketData\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.protocol.MarketItemR\x05items\"\xe7\x02\n" +
	"\x11ItemInstanceProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rdefinition_id\x18\x02 \x01(\rR\fdefinitionId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12#\n" +
	"\rlocation_type\x18\x04 \x01(\tR\flocationType\x12\x1f\n" +
	"\vlocation_id\x18\x05 \x01(\x04R\n" +
	"locationId\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\x04R\aownerId\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\t \x01(\tR\bcategory\x12\x1c\n" +
	"\tstackable\x18\n" +
	" \x01(\bR\tstackable\x12\x16\n" +
	"\x06volume\x18\v \x01(\x02R\x06volume\x12$\n" +
	"\x0emeta_data_json\x18\f \x01(\tR\fmetaDataJson\"^\n" +
	"\x0fInventoryUpdate\x12\x18\n" +
	"\acredits\x18\x01 \x01(\x03R\acredits\x121\n" +
	"\x05cargo\x18\x02 \x03(\v2\x1b.protocol.ItemInstanceProtoR\x05cargo\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\"p\n" +
	"\rServerCommand\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.protocol.PacketTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x9d\a\n" +
	"\x16PlayerMigrationPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x02R\brotation\x12\x0e\n" +
	"\x02vx\x18\x05 \x01(\x02R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x06 \x01(\x02R\x02vy\x12\x0e\n" +
	"\x02hp\x18\a \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\b \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06shield\x18\t \x01(\x05R\x06shield\x12\x1d\n" +
	"\n" +
	"max_shield\x18\n" +
	" \x01(\x05R\tmaxShield\x12*\n" +
	"\x11shield_regen_rate\x18\v \x01(\x02R\x0fshieldRegenRate\x12\x1f\n" +
	"\vweapon_type\x18\f \x01(\tR\n" +
	"weaponType\x12#\n" +
	"\rweapon_damage\x18\r \x01(\x05R\fweaponDamage\x12!\n" +
	"\fweapon_range\x18\x0e \x01(\x02R\vweaponRange\x12'\n" +
	"\x0fweapon_cooldown\x18\x0f \x01(\x02R\x0eweaponCooldown\x12%\n" +
	"\x0ecargo_capacity\x18\x10 \x01(\x05R\rcargoCapacity\x12<\n" +
	"\vcargo_items\x18\x11 \x03(\v2\x1b.protocol.ItemInstanceProtoR\n" +
	"cargoItems\x12!\n" +
	"\fmining_power\x18\x12 \x01(\x02R\vminingPower\x12!\n" +
	"\fmining_range\x18\x13 \x01(\x02R\vminingRange\x12\x1b\n" +
	"\tship_type\x18\x14 \x01(\tR\bshipType\x12\x1b\n" +
	"\tmax_speed\x18\x15 \x01(\x02R\bmaxSpeed\x12\x1b\n" +
	"\tturn_rate\x18\x16 \x01(\x02R\bturnRate\x12\x1d\n" +
	"\n" +
	"account_id\x18\x17 \x01(\x04R\taccountId\x12\x1f\n" +
	"\vplayer_name\x18\x18 \x01(\tR\n" +
	"playerName\x12\x18\n" +
	"\acredits\x18\x19 \x01(\x03R\acredits\x12\x1d\n" +
	"\n" +
	"session_id\x18\x1a \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"faction_id\x18\x1b \x01(\rR\tfactionId\x12\x15\n" +
	"\x06is_npc\x18\x1c \x01(\bR\x05isNpc\x12\x1f\n" +
	"\vai_behavior\x18\x1d \x01(\tR\n" +
	"aiBehavior\x12 \n" +
	"\fai_target_id\x18\x1e \x01(\x04R\n" +
	"aiTargetId\"\xcc\x01\n" +
	"\x15SystemTransferRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12(\n" +
	"\x10target_system_id\x18\x02 \x01(\rR\x0etargetSystemId\x12\x17\n" +
	"\aspawn_x\x18\x03 \x01(\x02R\x06spawnX\x12\x17\n" +
	"\aspawn_y\x18\x04 \x01(\x02R\x06spawnY\x12:\n" +
	"\apayload\x18\x05 \x01(\v2 .protocol.PlayerMigrationPayloadR\apayload\"t\n" +
	"\x16SystemTransferResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"'\n" +
	"\x11CreateCorpRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"l\n" +
	"\x12CreateCorpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\acorp_id\x18\x02 \x01(\rR\x06corpId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"2\n" +
	"\x11InviteCorpRequest\x12\x1d\n" +
	"\n" +
	"invitee_id\x18\x01 \x01(\x04R\tinviteeId\"*\n" +
	"\x0fJoinCorpRequest\x12\x17\n" +
	"\acorp_id\x18\x01 \x01(\rR\x06corpId\"p\n" +
	"\x12StartRefineRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x04R\tstationId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"N\n" +
	"\x10BuildShipRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x04R\tstationId\x12\x1b\n" +
	"\tship_type\x18\x02 \x01(\tR\bshipType\"\xa0\x01\n" +
	"\vVaultAction\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x04R\tstationId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x1d\n" +
	"\n" +
	"vault_type\x18\x04 \x01(\tR\tvaultType\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\"\xb6\x01\n" +
	"\vVaultStatus\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x04R\tstationId\x12B\n" +
	"\x0epersonal_items\x18\x02 \x03(\v2\x1b.protocol.ItemInstanceProtoR\rpersonalItems\x12D\n" +
	"\x0fcorporate_items\x18\x03 \x03(\v2\x1b.protocol.ItemInstanceProtoR\x0ecorporateItems\"p\n" +
	"\x11JoinCombatRequest\x12,\n" +
	"\x12combat_instance_id\x18\x01 \x01(\rR\x10combatInstanceId\x12-\n" +
	"\x13align_with_fleet_id\x18\x02 \x01(\x04R\x10alignWithFleetId*\xc3\x04\n" +
	"\n" +
	"PacketType\x12\x12\n" +
	"\x0ePACKET_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eC_AUTH_REQUEST\x10\x01\x12\x10\n" +
	"\fC_MOVE_INPUT\x10\x02\x12\x11\n" +
	"\rC_SHOOT_INPUT\x10\x03\x12\x10\n" +
	"\fC_MINE_INPUT\x10\x04\x12\x10\n" +
	"\fC_DOCK_INPUT\x10\x05\x12\x0f\n" +
	"\vC_BUY_INPUT\x10\x06\x12\x10\n" +
	"\fC_SELL_INPUT\x10\a\x12\n" +
	"\n" +
	"\x06C_PING\x10\b\x12\x13\n" +
	"\x0fS_AUTH_RESPONSE\x10\t\x12\x14\n" +
	"\x10S_WORLD_SNAPSHOT\x10\n" +
	"\x12\x14\n" +
	"\x10S_DELTA_SNAPSHOT\x10\v\x12\x12\n" +
	"\x0eS_DAMAGE_EVENT\x10\f\x12\x11\n" +
	"\rS_DEATH_EVENT\x10\r\x12\x12\n" +
	"\x0eS_CHAT_MESSAGE\x10\x0e\x12\x11\n" +
	"\rS_MARKET_DATA\x10\x0f\x12\x16\n" +
	"\x12S_INVENTORY_UPDATE\x10\x10\x12\n" +
	"\n" +
	"\x06S_PONG\x10\x11\x12\x19\n" +
	"\x15C_CREATE_CORP_REQUEST\x10\x12\x12\x1a\n" +
	"\x16S_CREATE_CORP_RESPONSE\x10\x13\x12\x19\n" +
	"\x15C_INVITE_CORP_REQUEST\x10\x14\x12\x17\n" +
	"\x13C_JOIN_CORP_REQUEST\x10\x15\x12\x1a\n" +
	"\x16C_START_REFINE_REQUEST\x10\x16\x12\x18\n" +
	"\x14C_BUILD_SHIP_REQUEST\x10\x17\x12\x12\n" +
	"\x0eC_VAULT_ACTION\x10\x18\x12\x12\n" +
	"\x0eS_VAULT_STATUS\x10\x19\x12\x19\n" +
	"\x15C_JOIN_COMBAT_REQUEST\x10\x1aB2Z0github.com/Home/galaxy-mmo/pkg/protocol;protocolb\x06proto3"

var (
	file_pkg_protocol_messages_proto_rawDescOnce sync.Once
	file_pkg_protocol_messages_proto_rawDescData []byte
)

func file_pkg_protocol_messages_proto_rawDescGZIP() []byte {
	file_pkg_protocol_messages_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_messages_proto_rawDesc), len(file_pkg_protocol_messages_proto_rawDesc)))
	})
	return file_pkg_protocol_messages_proto_rawDescData
}

var file_pkg_protocol_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_pkg_protocol_messages_proto_goTypes = []any{
	(PacketType)(0),                // 0: protocol.PacketType
	(*Packet)(nil),                 // 1: protocol.Packet
	(*AuthRequest)(nil),            // 2: protocol.AuthRequest
	(*MoveInput)(nil),              // 3: protocol.MoveInput
	(*ShootInput)(nil),             // 4: protocol.ShootInput
	(*MineInput)(nil),              // 5: protocol.MineInput
	(*DockInput)(nil),              // 6: protocol.DockInput
	(*BuyInput)(nil),               // 7: protocol.BuyInput
	(*SellInput)(nil),              // 8: protocol.SellInput
	(*Ping)(nil),                   // 9: protocol.Ping
	(*AuthResponse)(nil),           // 10: protocol.AuthResponse
	(*EntitySnapshot)(nil),         // 11: protocol.EntitySnapshot
	(*WorldSnapshot)(nil),          // 12: protocol.WorldSnapshot
	(*DeltaSnapshot)(nil),          // 13: protocol.DeltaSnapshot
	(*DamageEvent)(nil),            // 14: protocol.DamageEvent
	(*DeathEvent)(nil),             // 15: protocol.DeathEvent
	(*ChatMessage)(nil),            // 16: protocol.ChatMessage
	(*MarketItem)(nil),             // 17: protocol.MarketItem
	(*MarketData)(nil),             // 18: protocol.MarketData
	(*ItemInstanceProto)(nil),      // 19: protocol.ItemInstanceProto
	(*InventoryUpdate)(nil),        // 20: protocol.InventoryUpdate
	(*Pong)(nil),                   // 21: protocol.Pong
	(*ServerCommand)(nil),          // 22: protocol.ServerCommand
	(*PlayerMigrationPayload)(nil), // 23: protocol.PlayerMigrationPayload
	(*SystemTransferRequest)(nil),  // 24: protocol.SystemTransferRequest
	(*SystemTransferResponse)(nil), // 25: protocol.SystemTransferResponse
	(*CreateCorpRequest)(nil),      // 26: protocol.CreateCorpRequest
	(*CreateCorpResponse)(nil),     // 27: protocol.CreateCorpResponse
	(*InviteCorpRequest)(nil),      // 28: protocol.InviteCorpRequest
	(*JoinCorpRequest)(nil),        // 29: protocol.JoinCorpRequest
	(*StartRefineRequest)(nil),     // 30: protocol.StartRefineRequest
	(*BuildShipRequest)(nil),       // 31: protocol.BuildShipRequest
	(*VaultAction)(nil),            // 32: protocol.VaultAction
	(*VaultStatus)(nil),            // 33: protocol.VaultStatus
	(*JoinCombatRequest)(nil),      // 34: protocol.JoinCombatRequest
}
var file_pkg_protocol_messages_proto_depIdxs = []int32{
	0,  // 0: protocol.Packet.type:type_name -> protocol.PacketType
	11, // 1: protocol.WorldSnapshot.entities:type_name -> protocol.EntitySnapshot
	11, // 2: protocol.DeltaSnapshot.updated_entities:type_name -> protocol.EntitySnapshot
	17, // 3: protocol.MarketData.items:type_name -> protocol.MarketItem
	19, // 4: protocol.InventoryUpdate.cargo:type_name -> protocol.ItemInstanceProto
	0,  // 5: protocol.ServerCommand.type:type_name -> protocol.PacketType
	19, // 6: protocol.PlayerMigrationPayload.cargo_items:type_name -> protocol.ItemInstanceProto
	23, // 7: protocol.SystemTransferRequest.payload:type_name -> protocol.PlayerMigrationPayload
	19, // 8: protocol.VaultStatus.personal_items:type_name -> protocol.ItemInstanceProto
	19, // 9: protocol.VaultStatus.corporate_items:type_name -> protocol.ItemInstanceProto
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_protocol_messages_proto_init() }
func file_pkg_protocol_messages_proto_init() {
	if File_pkg_protocol_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_messages_proto_rawDesc), len(file_pkg_protocol_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_messages_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_messages_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_messages_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_messages_proto_msgTypes,
	}.Build()
	File_pkg_protocol_messages_proto = out.File
	file_pkg_protocol_messages_proto_goTypes = nil
	file_pkg_protocol_messages_proto_depIdxs = nil
}
